title: Famicom Reproduction
description: Recording of my Famicom/NES reproduction work.
author: Maximaas
github: https://github.com/maximass
about: A old school retro freak.
disqus_shortname: fcrepro
avatar_url: static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/xxx"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/xxx"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/maximaas"

share:
  twitter_username: agu1smakmun6
  fb_appid: 17497818565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://maximaas.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
